[package]
name = "automata"
version = "0.1.0"
edition = "2021"

[dependencies]
ops_derive = { path = "./ops_derive" }
ops_derive_consts = { path = "./ops_derive_consts" }

[workspace]
members = [ "ops_derive" , "ops_derive_consts"]
